# Generated by Django 2.2.6 on 2019-11-10 01:25

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_botaccount'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playersearch',
            name='unique_active_search',
        ),
        migrations.AlterField(
            model_name='playersearch',
            name='state',
            field=django_fsm.FSMField(choices=[('searching', 'Searching for a match'), ('cancelled', 'Cancelled search'), ('found_match', 'Found a match'), ('accepted_match', 'Accepted the match'), ('lobby_setup', 'Setting up a lobby'), ('in_lobby', 'In lobby'), ('success', 'Successfully matched')], default='searching', max_length=50, protected=True),
        ),
        migrations.AddConstraint(
            model_name='playersearch',
            constraint=models.UniqueConstraint(condition=models.Q(state__in=['searching', 'found_match', 'accepted_match', 'lobby_setup', 'in_lobby']), fields=('user',), name='unique_active_search'),
        ),
    ]
