# Generated by Django 2.2.6 on 2019-11-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191112_1724'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='heromatchup',
            constraint=models.UniqueConstraint(fields=('hero', 'other_hero'), name='only_one_value_per_pair'),
        ),
    ]
