# Generated by Django 2.2.6 on 2019-11-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191115_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='aliases',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='counters',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='easy_lanes',
        ),
        migrations.AddField(
            model_name='hero',
            name='pro_matchups',
            field=models.ManyToManyField(blank=True, related_name='_hero_pro_matchups_+', to='core.Hero'),
        ),
        migrations.DeleteModel(
            name='HeroMatchup',
        ),
    ]
