# Generated by Django 2.2.6 on 2019-12-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191115_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='botaccount',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='botaccount',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='botaccount',
            constraint=models.UniqueConstraint(
                condition=models.Q(is_main=True), fields=('is_main', ), name='only_one_main_bot'
            ),
        ),
    ]
