# Generated by Django 2.2.6 on 2019-10-25 10:52

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('opendota_id', models.IntegerField(unique=True)),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64, null=True), blank=True, null=True, size=None)),
                ('is_traditional_mid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedHero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_meta', models.BooleanField()),
                ('auto_counterpick', models.BooleanField()),
                ('auto_stomp', models.BooleanField()),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Hero')),
                ('total_bans', models.ManyToManyField(blank=True, related_name='_selectedhero_total_bans_+', to='core.Hero')),
                ('total_matchups', models.ManyToManyField(blank=True, related_name='_selectedhero_total_matchups_+', to='core.Hero')),
                ('unwanted_matchups', models.ManyToManyField(blank=True, related_name='_selectedhero_unwanted_matchups_+', to='core.Hero')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wanted_matchups', models.ManyToManyField(blank=True, related_name='_selectedhero_wanted_matchups_+', to='core.Hero')),
            ],
        ),
        migrations.CreateModel(
            name='HeroMatchup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantage', models.FloatField()),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Hero')),
                ('other_hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Hero')),
            ],
        ),
    ]
