# Generated by Django 2.2.6 on 2019-10-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedhero',
            name='total_bans',
        ),
        migrations.RemoveField(
            model_name='selectedhero',
            name='unwanted_matchups',
        ),
    ]
