# Generated by Django 2.2.6 on 2019-11-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191104_1208'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playersearch',
            name='unique_active_search',
        ),
        migrations.AddField(
            model_name='playersearch',
            name='channel_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='playersearch',
            constraint=models.UniqueConstraint(condition=models.Q(state__in={'accepted_match', 'started_search', 'found_match'}), fields=('user',), name='unique_active_search'),
        ),
    ]
