---

version: 2

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build web
          command: docker build -t rg.fr-par.scw.cloud/ipeterov/dotapracc-web:latest .

      - run:
          name: Build nginx
          command: docker build -t rg.fr-par.scw.cloud/ipeterov/dotapracc-nginx:latest .

      - run:
          name: Publish images
          command: |
            docker login rg.fr-par.scw.cloud/ipeterov -u nologin -p "$DOCKER_REGISTRY_TOKEN"
            docker push rg.fr-par.scw.cloud/ipeterov/dotapracc-web:latest
            docker push rg.fr-par.scw.cloud/ipeterov/dotapracc-nginx:latest
  deploy:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Keyscan (HACK)
          command: ssh-keyscan -H dotapra.cc >> ~/.ssh/known_hosts
      - run:
          name: Deploy to Scaleway
          command: |
            set -x
            docker-compose -H ssh://root@dotapra.cc pull
            docker-compose -H ssh://root@dotapra.cc up -d

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
