version: 2
  jobs:
    build:
      docker:
        - image: circleci/buildpack-deps:stretch
      steps:
        - checkout
        - setup_remote_docker

        - run:
            name: Build web
            command: docker build -t $WEB_IMAGE_NAME:latest .

        - run:
            name: Build nginx
            command: docker build -t $NGINX_IMAGE_NAME:latest .

        - run:
            name: Publish images
            command: |
              docker login rg.fr-par.scw.cloud/ipeterov -u nologin -p "DOCKER_REGISTRY_TOKEN"
              docker push $WEB_IMAGE_NAME:latest
              docker push $NGINX_IMAGE_NAME:latest

  workflows:
    version: 2
    build-master:
      jobs:
        - build:
            filters:
              branches:
                only: master
