---

version: 2

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build images
          command: docker-compose -f docker-compose.yml build

      - run:
          name: Push images
          command: |
            docker login rg.fr-par.scw.cloud/ipeterov -u nologin -p "$DOCKER_REGISTRY_TOKEN"
            docker-compose -f docker-compose.yml push

  deploy:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - add_ssh_keys
      - run:
          name: Keyscan (HACK)
          command: ssh-keyscan -H dotapra.cc >> ~/.ssh/known_hosts
      - run:
          name: Deploy to Scaleway
          environment:
            DOCKER_CLIENT_TIMEOUT: 120
            COMPOSE_HTTP_TIMEOUT: 120
          command: |
            set -x
            docker login rg.fr-par.scw.cloud/ipeterov -u nologin -p "$DOCKER_REGISTRY_TOKEN"
            docker-compose -H ssh://root@dotapra.cc pull
            docker-compose -H ssh://root@dotapra.cc up -d

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
